### ISSUE TITLE
Not able to run locally - 404 on /api/readability

### ISSUE THREAD

**Issue by dmitrym0** [Gowee/readability-bot#4]
Hello folks,

I tried to run this locally:

1. `npm install`
2. `npm run dev`

However when I try to hit http://localhost:5000/api/readability?url=http%3A%2F%2Fgoogle.com in the browser I get a 404. What am I missing?

**Comment by Gowee** [comment]
Hello.

The (somewhat misleading) package.json is generated automatically by Svelte for the front-end web page.

To spin up the whole app with API service, `npx vercel dev`.

And if you are gonna run a Telegram bot, do not forget to [set the webhook](https://core.telegram.org/bots/webhooks#how-do-i-set-a-webhook-for-either-type) callback URL to your Vercel app.

Thanks for your feedback, I will update the README to doc this procedure.

**Comment by dmitrym0** [comment]
@Gowee appreciate it! 

My goal was to try latest `Mozilla/readability` because readability-bot results differ from the actual Firefox reader mode. I bumped it up to 0.4.4 and it's still differs from what "reader mode" shows. Any idea why that might be?

**Comment by Gowee** [comment]
I am not sure what the difference is.

If you mean the webpage style, it is set separately, irrelevant to readability-js. If you mean the webpage content/element, I have no idea. https://github.com/mozilla/readability/issues/472#issuecomment-406308538 suggests that the standalone version might not be exactly the same as the one used in Firefox.

**Comment by dmitrym0** [comment]
Yeah, I'm talking about web page content. 

Here's the reader mode in Firefox 113:

<img width="2032" alt="image" src="https://github.com/Gowee/readability-bot/assets/707020/44cc83f3-0c86-421d-9bba-ba36d3e2ab95">


and here's the bot:

<img width="2032" alt="image" src="https://github.com/Gowee/readability-bot/assets/707020/f6a7743e-a9ec-4c88-9d04-d38f0b92cc33">


Interestingly, a few days days ago when I captured the PDF (using readability-bot) this is what it looked like:

<img width="1072" alt="image" src="https://github.com/Gowee/readability-bot/assets/707020/5e463d39-7c13-40b7-a7e4-1bf42d3be8bb">


Here's the URL: https://medium.com/awesome-cloud/aws-difference-between-amazon-aurora-and-amazon-rds-comparison-aws-aurora-vs-aws-rds-databases-60a69dbec41f


I wonder if maybe medium is serving something different based on the User-agent.

**Comment by Gowee** [comment]
Closing. I cannot help more. And it is actually out of the scope of the project. Thanks for your feedback again.
